<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>@yield('title')</title>
    <style>
        @page {
            margin: 40px 50px 80px 50px;
        }
        header {
            margin-bottom: 30px;
            border-bottom: 2px solid #CC0000;
            padding-bottom: 20px;
        }
        footer {
            position: fixed;
            bottom: -60px;
            left: 0;
            right: 0;
            height: 50px;
            text-align: center;
            font-size: 10px;
            color: #b0a8a0;
            border-top: 1px solid #ece8e3;
            padding-top: 10px;
        }
        body {
            font-family: 'Helvetica', sans-serif;
            font-size: 12px;
            color: #0f0f0f;
            line-height: 1.5;
        }
        .logo-container {
            float: left;
            width: 200px;
            text-align: left;
        }
        .logo-container img {
            max-width: 180px;
            height: auto;
        }
        .address-container {
            float: right;
            text-align: right;
            width: 350px;
            font-size: 10px;
            color: #5c5550;
            line-height: 1.4;
        }
        .clear {
            clear: both;
        }
        .meta-section {
            margin-top: 20px;
            margin-bottom: 30px;
            padding: 15px;
            background-color: #f8f7f5;
            border-radius: 5px;
        }
        .meta-item {
            display: inline-block;
            width: 32%;
            font-size: 11px;
        }
        .meta-label {
            font-weight: bold;
            color: #a09890;
            text-transform: uppercase;
            font-size: 9px;
            margin-bottom: 2px;
        }
        .report-title {
            font-size: 20px;
            font-weight: bold;
            color: #CC0000;
            margin-bottom: 5px;
            text-transform: uppercase;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f8f7f5;
            color: #5c5550;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 10px;
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ece8e3;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #f5f1ed;
            vertical-align: top;
        }
        .status-badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
            display: inline-block;
        }
        .status-available { background-color: #eaf3de; color: #3B6D11; }
        .status-assigned { background-color: #e6f1fb; color: #185FA5; }
        .status-damaged { background-color: #fcebeb; color: #A32D2D; }
        .section-header {
            font-size: 14px;
            font-weight: bold;
            color: #0f0f0f;
            margin-top: 20px;
            margin-bottom: 10px;
            border-bottom: 1px solid #ece8e3;
            padding-bottom: 5px;
        }
        .pagenum:before {
            content: counter(page);
        }
    </style>
</head>
<body>
    <header>
        <div class="logo-container">
            <img src="{{ public_path('images/grey-apple-events-logo.png') }}" alt="Grey Apple Events">
        </div>
        <div class="address-container">
            <strong>Location:</strong> Thome Estate, Mbuni Drive, MD05, Nairobi, Kenya.<br>
            <strong>Alternative:</strong> Ruaraka Housing Estate, 23 USIU Rd, Nairobi.<br>
            <strong>Email:</strong> info@greyapple.co.ke<br>
            <strong>Phone:</strong> +254 722 289648
        </div>
        <div class="clear"></div>
    </header>

    <footer>
        Grey Apple IMS — Professional Inventory Management | Page <span class="pagenum"></span>
    </footer>

    <div class="content">
        <div class="report-title">@yield('report_name')</div>
        
        <div class="meta-section">
            <div class="meta-item">
                <div class="meta-label">Reference Number</div>
                <div>{{ $ref_no ?? 'GA-RPT-' . date('YmdHis') }}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Date Generated</div>
                <div>{{ date('D, j M Y, g:i a') }}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Generated By</div>
                <div>{{ auth()->user()->name }}</div>
            </div>
            <div class="clear"></div>
        </div>

        @yield('content')

        <div style="margin-top: 50px;">
            <div style="float: left; width: 200px; border-top: 1px solid #000; text-align: center; padding-top: 5px; font-size: 10px;">
                Authorized Signature
            </div>
            <div style="float: right; width: 200px; border-top: 1px solid #000; text-align: center; padding-top: 5px; font-size: 10px;">
                Warehouse Manager
            </div>
            <div class="clear"></div>
        </div>
    </div>
</body>
</html>
